name: flutter_5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  provider: ^6.1.1
  hive: ^2.2.3
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  hive_flutter: ^1.1.0

flutter:
  uses-material-design: true
